//
//  ClipboardPasteInjector.swift
//  magic-voice
//
//  Magic Voice — text injection via clipboard overwrite + simulated ⌘V.
//

import AppKit
import Foundation

/// Injects text by temporarily replacing the system clipboard contents and
/// posting a synthetic ⌘V keystroke. The original clipboard is restored after
/// a short delay to minimise user-visible disruption.
///
/// This adapter always reports `succeeded: true` because the paste keystroke is
/// fire-and-forget — there is no synchronous confirmation that the target field
/// accepted the paste.
@MainActor
final class ClipboardPasteInjector: TextInjecting {

    private let clipboardRestorer = ClipboardRestorer()

    @discardableResult
    func inject(_ text: String) -> InjectionResult {
        guard !text.isEmpty else {
            return .failure(reason: "Empty text", text: text)
        }

        let savedSnapshot = clipboardRestorer.snapshot()
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: Self.transientClipboardType)
        item.setData(Data(), forType: Self.autoGeneratedClipboardType)
        pasteboard.writeObjects([item])

        postCommandV()
        clipboardRestorer.restore(savedSnapshot, after: 0.25)

        // The paste keystroke is asynchronous; we report success optimistically.
        return .success(adapter: .clipboardPaste, text: text)
    }

    // MARK: - Private helpers

    private func postCommandV() {
        let source = CGEventSource(stateID: .privateState)
        let commandKey: CGKeyCode = 0x37
        let vKey: CGKeyCode = 0x09

        let commandDown = CGEvent(keyboardEventSource: source, virtualKey: commandKey, keyDown: true)
        let vDown      = CGEvent(keyboardEventSource: source, virtualKey: vKey,        keyDown: true)
        let vUp        = CGEvent(keyboardEventSource: source, virtualKey: vKey,        keyDown: false)
        let commandUp  = CGEvent(keyboardEventSource: source, virtualKey: commandKey,  keyDown: false)

        commandDown?.flags = .maskCommand
        vDown?.flags       = .maskCommand
        vUp?.flags         = .maskCommand

        commandDown?.post(tap: .cghidEventTap)
        vDown?.post(tap: .cghidEventTap)
        vUp?.post(tap: .cghidEventTap)
        commandUp?.post(tap: .cghidEventTap)
    }

    private static let transientClipboardType =
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedClipboardType =
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}
